# COMMON
INPUT_DIR: "/images/"
MD_FILE: "md_out.json"
LOWER_CONF: 0.05
# MEGADETECTOR
MD_MODEL: "md_v5a.0.0.pt"
IMG_FILE: 
RECURSIVE: True
RELATIVE_FILENAMES: True
QUIET: False
IMAGE_QUEUE: False
THRESHOLD: 0.01
CHECKPOINT_FREQ: 100
CHECKPOINT_FILE: 
NCORES: 
# BOX
BLANK_DIR: "blank"
SUBFOLDER: True
# BOX - MATRYOSHKA
OVERLAP: 0.3
EDGE_DIST: 0.02
MIN_EDGES: 0
UPPER_CONF: 0.9
# SNIP
SNIP_DIR: "snips"
SNIP_SIZE: 600
# EXIF
EN_FILE: "mewc_out.pkl"
EN_CSV: "mewc_out.csv"
